Repository hmcts/ccd-test-stubs-service, pull requests merged in 2020-01, with the labels that each got.

#32 Rdm 6929 - ccd-test-stubs-service is not building on master
  .travis.yml
  Dockerfile
  build.gradle
  charts/ccd-test-stubs-service/Chart.yaml
  charts/ccd-test-stubs-service/values.yaml
Labels: ns:ccd-test-stubs-service-pr-32

#34 RDM-7114: ccd-test-stubs-service is not building on master. 2020 vuln…
  build.gradle
Labels: ns:ccd-test-stubs-service-pr-34

#33 Rdm 2714 pr
  wiremock/mappings/callback_overriding_state_as_data.json
  wiremock/mappings/callback_overriding_state_as_top_level_property.json
  wiremock/mappings/callback_returning_only_data.json
Labels: ns:ccd-test-stubs-service-pr-33

#35 RDM-6398: add stubs for callbacks returning errors
  wiremock/mappings/callback_returning_errors_and_warnings.json
  wiremock/mappings/callback_returning_warnings.json
Labels: ns:ccd, rel:ccd-test-stubs-service-pr-35

#40 Resolve CVE-2020-5398
  build.gradle
Labels: ns:ccd, rel:ccd-test-stubs-service-pr-40

#37 RDM-7389 bump versions
  charts/ccd-test-stubs-service/Chart.yaml
  charts/ccd-test-stubs-service/requirements.yaml
Labels: ns:ccd, rel:ccd-test-stubs-service-pr-37

#41 RDM-7389 enable AKS
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-test-stubs-service-pr-41

#36 Rdm 6436 - stub service improvements
  CCD_CNP_27_With_Callbacks.xlsx
  README.md
  src/functionalTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/StubFunctionalTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java
  src/smokeTest/java/uk/gov/hmcts/reform/ccd/test/stubs/service/StubSmokeTest.java
  wiremock/mappings/ccd/callback_about_to_start.json
  wiremock/mappings/ccd/callback_about_to_submit.json
  wiremock/mappings/ccd/callback_dynamiclist.json
  wiremock/mappings/ccd/callback_mid_event.json
  wiremock/mappings/ccd/callback_overriding_state_as_data.json
  wiremock/mappings/ccd/callback_overriding_state_as_top_level_property.json
  wiremock/mappings/ccd/callback_returning_errors.json
  wiremock/mappings/ccd/callback_returning_errors_and_warnings.json
  wiremock/mappings/ccd/callback_returning_only_data.json
  wiremock/mappings/ccd/callback_returning_warnings.json
  wiremock/mappings/ccd/callback_submitted.json
  wiremock/mappings/idam/idam_get_details.json
  wiremock/mappings/idam/idam_get_token.json
  wiremock/mappings/idam/idam_logout.json
Labels: ns:ccd, rel:ccd-test-stubs-service-pr-36

#42 RDM-7389 add ingress
  charts/ccd-test-stubs-service/Chart.yaml
  charts/ccd-test-stubs-service/values.yaml
Labels: ns:ccd, rel:ccd-test-stubs-service-pr-42

#43 RDM-7389 disableLegacyDeploymentOnAAT
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-test-stubs-service-pr-43

#44 RDM-7389 Rm aat ASE
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/preview.tfvars
  infrastructure/sandbox.tfvars
  infrastructure/variables.tf
Labels: ns:ccd, rel:ccd-test-stubs-service-pr-44
