Repository hmcts/ccd-test-stubs-service, pull requests merged in 2021-12, with the labels that each got.

#118 RDM-12764 - Callback to populate case details for GlobalSearch case type
  wiremock/mappings/ccd/callback_about_to_submit_party_info_modified.json
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-118

#119 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-119

#120 update log4j
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-120

#121 CCD-2351: Update log4j version to 2.16.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-121

#122 CCD-2231: Updated CVE suppression dates
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-122

#123 CCD-2374: Update log4j version to 2.17.0
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-123
