Repository hmcts/ccd-test-stubs-service, pull requests merged in 2021-08, with the labels that each got.

#102 Suppress CVE-2021-28170
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-102

#103 RDM-12683 Add location reference data
  build.gradle
  wiremock/mappings/refdata/get_building_locations.json
  wiremock/mappings/refdata/get_org_services.json
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-103

#104 Resolve CVE-2021-28170
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-104
