Repository hmcts/ccd-test-stubs-service, pull requests merged in 2021-05, with the labels that each got.

#84 Rdm 10923
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/config/WireMockServerConfig.java
  src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/wiremock/extension/DynamicRoleAssignmentsResponseTransformer.java
  src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/wiremock/extension/DynamicRoleAssignmentsResponseTransformerTest.java
  wiremock/mappings/roleassignmentservice/get_role_assignments.json
  wiremock/mappings/roleassignmentservice/get_role_assignments_expired_result.json
  wiremock/mappings/roleassignmentservice/get_role_assignments_not_found.json
  wiremock/mappings/roleassignmentservice/post_role_assignments_query_1.json
  wiremock/mappings/roleassignmentservice/post_role_assignments_query_2.json
  wiremock/mappings/roleassignmentservice/post_role_assignments_query_3.json
  wiremock/mappings/roleassignmentservice/post_role_assignments_query_expired.json
  wiremock/mappings/roleassignmentservice/post_role_assignments_query_notFound_3.json
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-84

#87 CCD-1219 : Updated CVE suppress until date by 1 month
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-87

#88 CCD-1232 CVE-2021-22112 (Test Stubs Service)
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-88
