Repository hmcts/ccd-test-stubs-service, pull requests merged in 2021-07, with the labels that each got.

#93 tidy up dependency-check-suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-93

#94 suppress CVE
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-94

#95 fix for CVE-2021-27568
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-95

#98 fix for CVE-2021-33037
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-98

#100 integrate fortify scan into nightly pipelines
  Jenkinsfile_nightly
  build.gradle
  config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-100

#101 CCD-1330: Updated CVE suppression dates to 25/08/2021
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-101
