Repository hmcts/ccd-test-stubs-service, pull requests merged in 2022-04, with the labels that each got.

#139 spring-framework.version update to 5.3.18 from 5.3.15
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-139

#142 jackson.version update for CVE-2020-36518
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-142

#143 New Dates
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-143

#144 spring-core-5.3.18.jar dependency suppression
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-144
