Repository hmcts/ccd-test-stubs-service, pull requests merged in 2022-09, with the labels that each got.

#183 Suppress CVE-2022-25857 in suppressions.xml
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-183

#182 CCD-3577 Cleanup CVE Suppressions remove CVE-2018-1258, CVE-2022-3391…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-182

#184 CCD-3431 CVE-2022-34305 tomcat upgrade, suppression removed
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-184

#178 HMAN-368 - Add next hearing date callbacks
  wiremock/mappings/ccd/callback_nextHearingDate.json
  wiremock/mappings/ccd/callback_nextHearingDateIsInPast.json
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-178

#186 CCD-3682 Suppressions for snakeyaml CVE-2022-38751 CVE-2022-38750 CVE…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-186

#177 CCD-3152 Adding new callback for injected data
  wiremock/mappings/ccd/callback_get_case_injectedData.json
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-177

#173 Remove version number
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-173

#189 CCD-3736: Suppress CVE-2022-38752
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-189
