Repository hmcts/ccd-test-stubs-service, pull requests merged in 2022-10, with the labels that each got.

#185 CCD-3658-CVE-2022-25857-fix
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-185

#190 CCD-3773 Conditionally cleanup helm releases on PRs
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-190, keep-helm

#193 CCD-3820 CVE-2022-42889 suppression
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-193

#192 CCD-3776 CVE-2022-42003 and CVE-2022-42004 jackson upgraded to 2.14.0…
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-192

#194 CCD-3820:CVE-2022-42889-Fix
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-194
