Repository hmcts/ccd-test-stubs-service, pull requests merged in 2022-12, with the labels that each got.

#206 CCD-4043 Fasterxml Jackson Upgrade
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-206

#209 Ccd 4017 helm chart upgrades
  charts/ccd-test-stubs-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-209

#207 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-207
