Repository hmcts/ccd-test-stubs-service, pull requests merged in 2022-07, with the labels that each got.

#160 CCD-3449 : Update dependency-check-suppressions.xml (CVE-2022-33915)
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-160

#162 CCD-3434 Upgrade Java, postgresql and redis configurations
  charts/ccd-test-stubs-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-162

#159 CCD-965: Remove Temporary Sonar Exclusions ccd-test-stubs-service
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-159

#165 CCD-3536: CVE-2022-31569 suppress
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-165

#169 CCD-3515 CVE-2022-22976 fixed by upgrading spring-security-crypto to …
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-169

#172 CCD-3524: Fix for CVE-2021-22119
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-172

#170 CCD-3561 Upgrade Java and Node JS versions in chart for all the respe…
  charts/ccd-test-stubs-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-170

#164 CCD-3504 Upgrade to latest java plugin - java plugin upgraded to 0.12…
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-164

#166 CCD-3535 callback TTL.Suspended to uppercase
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/config/WireMockServerConfig.java
  src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/wiremock/extension/AbstractTTLResponseTransformer.java
  src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/wiremock/extension/DynamicTTLNullResponseTransformer.java
  src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/wiremock/extension/DynamicTTLRemoveResponseTransformer.java
  src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/wiremock/extension/DynamicTTLUppercaseResponseTransformer.java
  src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/wiremock/extension/DynamicTTLNullResponseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/wiremock/extension/DynamicTTLRemoveResponseTransformerTest.java
  src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/wiremock/extension/DynamicTTLUppercaseResponseTransformerTest.java
  wiremock/mappings/ccd/callback_ttl_null.json
  wiremock/mappings/ccd/callback_ttl_removed.json
  wiremock/mappings/ccd/callback_ttl_suspended_to_uppercase.json
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-166
