Repository hmcts/ccd-test-stubs-service, pull requests merged in 2022-11, with the labels that each got.

#199 CCD-3917 CVE-2022-31690, CVE-2022-31690 CCD-3918 CVE-2022-42252 Suppr…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-199

#196 CCD-3802 Update to fortify-client version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-196

#200 CCD-3918 CVE-2022-42252
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-test-stubs-service-pr-200

#201 CCD-3917 Spring Security Upgrade
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-201

#203 CCD-3857: Fix for Test-stubs Wiremocks not working on AAT/Preview
  build.gradle
  src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/config/ApplicationConfig.java
  src/main/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseController.java
  src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-test-stubs-service-pr-203

#188 CCD-3533 Add suppressCves task
  .github/workflows/dependency-check.yml
  build.gradle
  gradle/suppress.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-188
