Repository hmcts/ccd-test-stubs-service, pull requests merged in 2022-06, with the labels that each got.

#151 CCD-3355: Dockerfile Fortify fix
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-151

#152 CCD-3376 Update java chart version
  charts/ccd-test-stubs-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-152

#150 CVE-2022-29885: ccd-test-stubs-service fix
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-150

#154 CCD-3248 Monthly Review of All Security Flags - Commented out all sup…
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-154

#156 Add comment to suppressions.xml
  charts/ccd-test-stubs-service/Chart.yaml
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-156

#158 Update dependency-check-suppressions.xml added temporary suppression for CVE-2022-34305
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-158
