Repository hmcts/ccd-test-stubs-service, pull requests merged in 2023-11, with the labels that each got.

#281 add environment variable for jwt expiration
  src/main/resources/application.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-281

#226 CCD-4454 : CVE-2022-1471 Fix
  build.gradle
  dependency-check-suppressions.xml
  src/test/java/uk/gov/hmcts/reform/ccd/test/stubs/service/controllers/StubResponseControllerTest.java
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-226

#277 CCD-4970 : Fix CVE-2020-8908
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-277

#279 CCD-4994 : Fix-CVE-2023-36478
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-279
