Repository hmcts/ccd-test-stubs-service, pull requests merged in 2023-01, with the labels that each got.

#211 CCD-4163 Bump rse-gradle-java-plugin version
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-211

#213 Update Chart.yaml
  charts/ccd-test-stubs-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-213

#217 CCD-4283: Bump gradle-java-plugin to 0.12.40
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-217
