Repository hmcts/ccd-test-stubs-service, pull requests merged in 2023-10, with the labels that each got.

#273 CCD-4845 renovate config
  .github/renovate.json
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-273

#214 CCD-4214 Remove discoveryComposite from health endpoint
  .github/renovate.json
  build.gradle
  src/main/resources/application.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-214

#270 CCD-4737 : Fix CVE-2023-28709 (Bumped version of Tomcat)
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-270

#276 CCD-4949:Fix - Versions below java-logging: 6.0.1
  build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-276
