Repository hmcts/ccd-test-stubs-service, pull requests merged in 2023-02, with the labels that each got.

#219 CCD-4312 CVE-2022-45143 Tomcat Upgrade
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-219

#222 CCD-4267
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-222

#221 CCD-4317 Upgrade base charts
  charts/ccd-test-stubs-service/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-221
