Repository hmcts/ccd-test-stubs-service, pull requests merged in 2024-04, with the labels that each got.

#293 CCD-5160: bumped jackson.version to 2.16.0
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-293

#292 Updating wiremock as there are 2 seperate CVEs for this issue
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-292

#291 CCD-5204 updated wiremock version to resolve CVE
  dependency-check-suppressions.xml
Labels: ns:ccd, prd:ccd, rel:ccd-test-stubs-service-pr-291
